language: python

python:
  - 3.6
  - 3.7-dev
  - nightly

services: postgresql

env:
  - DJANGO=1.11.5

before_install:
  - export DJANGO_SETTINGS_MODULE=JestemGraczem.settings
  - export PYTHONPATH=$HOME/builds/otlet/JestemGraczem.pl
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate
  - python manage.py makemigrations