# Generated by Django 2.0.6 on 2018-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESportTwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, verbose_name='Nazwa kanału')),
                ('twitch_id', models.IntegerField(verbose_name='Twitch ID')),
            ],
            options={
                'verbose_name': 'Kanały eSport Twitch',
                'verbose_name_plural': 'Kanały eSport Twitch',
            },
        ),
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, verbose_name='Nazwa')),
                ('twitch_id', models.IntegerField(null=True, verbose_name='Twitch ID')),
                ('add_date', models.DateTimeField(verbose_name='Data publikacji')),
                ('partner', models.BooleanField(default=False, verbose_name='Partner')),
                ('banned', models.BooleanField(default=False, verbose_name='Blokada')),
                ('accepted', models.BooleanField(default=False, verbose_name='Opublikowany')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Kanał YouTube')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Kanały Twitch.tv',
                'verbose_name_plural': 'Kanały Twitch.tv',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('add_date', models.DateTimeField(verbose_name='Data publikacji')),
                ('video_id', models.CharField(max_length=23, verbose_name='ID Wideo')),
                ('accepted', models.BooleanField(default=False, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Filmy na YouTube',
                'verbose_name_plural': 'Filmy na YouTube',
            },
        ),
    ]
