# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESportTwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('twitch_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kanały eSport Twitch',
                'verbose_name_plural': 'Kanały eSport Twitch',
            },
        ),
        migrations.RemoveField(
            model_name='mixer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='twitch',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='owner',
        ),
    ]
