# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20170809_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitch',
            options={'verbose_name': 'Kanały Twitch.tv', 'verbose_name_plural': 'Kanały Twitch.tv'},
        ),
    ]
