# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20170726_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name': 'Filmy na YouTube', 'verbose_name_plural': 'Filmy na YouTube'},
        ),
        migrations.AddField(
            model_name='twitch',
            name='twitch_id',
            field=models.IntegerField(null=True),
        ),
    ]
