# Generated by Django 2.0.2 on 2018-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_auto_20170810_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitch',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtube',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
