# Generated by Django 2.0.6 on 2018-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20180220_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mixer',
        ),
        migrations.AlterField(
            model_name='esporttwitch',
            name='name',
            field=models.CharField(max_length=23, verbose_name='Nazwa kanału'),
        ),
        migrations.AlterField(
            model_name='esporttwitch',
            name='twitch_id',
            field=models.IntegerField(verbose_name='Twitch ID'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Opublikowany'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='add_date',
            field=models.DateTimeField(verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Blokada'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='name',
            field=models.CharField(max_length=23, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='twitch_id',
            field=models.IntegerField(null=True, verbose_name='Twitch ID'),
        ),
        migrations.AlterField(
            model_name='twitch',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kanał YouTube'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Opublikowany'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='add_date',
            field=models.DateTimeField(verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(max_length=23, verbose_name='ID Wideo'),
        ),
    ]
