# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesServersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('description', models.TextField()),
                ('official', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Serwery gier',
                'verbose_name_plural': 'Serwery gier',
            },
        ),
    ]
