# Generated by Django 2.0.6 on 2018-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('variable', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
        migrations.CreateModel(
            name='GamesServersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('description', models.TextField()),
                ('official', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Serwery gier',
                'verbose_name_plural': 'Serwery gier',
            },
        ),
        migrations.CreateModel(
            name='LinkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tytuł')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('image', models.URLField(null=True, verbose_name='Miniatura')),
                ('accepted', models.BooleanField(default=False, verbose_name='Opublikowany')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Artykuł sponsorowany')),
                ('iframe', models.BooleanField(default=True, verbose_name='Ramka')),
            ],
            options={
                'verbose_name': 'LinkBlog',
                'verbose_name_plural': 'LinkBlog',
            },
        ),
    ]
