# Generated by Django 2.1 on 2018-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
    ]
