# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('variable', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
    ]
