# Generated by Django 2.1 on 2018-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180826_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'RSS',
                'verbose_name_plural': 'RSS',
            },
        ),
    ]
