# Generated by Django 2.0.6 on 2018-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, verbose_name='Tytuł')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('accepted', models.BooleanField(default=False, verbose_name='Opublikowany')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Artykuł sponsorowany')),
                ('iframe', models.BooleanField(default=True, verbose_name='Ramka')),
            ],
            options={
                'verbose_name': 'LinkBlog',
                'verbose_name_plural': 'LinkBlog',
            },
        ),
    ]
