# Generated by Django 2.1 on 2018-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_linkblog_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblog',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='Partner'),
        ),
    ]
