# Generated by Django 2.0.6 on 2018-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_linkblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblog',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Tytuł'),
        ),
    ]
